from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SUMMARY_CSV = ROOT / "multiview_method_comparison_analysis" / "outputs" / "harmonized_method_summary.csv"
DEFAULT_OUTPUT_PNG = ROOT / "multiview_method_comparison_analysis" / "outputs" / "top5_two_vs_three_method_comparison.png"
DEFAULT_OUTPUT_CSV = ROOT / "multiview_method_comparison_analysis" / "outputs" / "top5_two_vs_three_method_comparison.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the top 5 two-view and three-view coalition methods on the shared strict-quality metric."
    )
    parser.add_argument(
        "--summary-csv",
        default=str(DEFAULT_SUMMARY_CSV),
        help="CSV generated by build_harmonized_method_comparison.py.",
    )
    parser.add_argument(
        "--output-png",
        default=str(DEFAULT_OUTPUT_PNG),
        help="Where to save the comparison figure.",
    )
    parser.add_argument(
        "--output-csv",
        default=str(DEFAULT_OUTPUT_CSV),
        help="Where to save the top-5 comparison table.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=5,
        help="How many methods to keep per view count.",
    )
    return parser.parse_args()


def parse_float(raw: str) -> float:
    text = str(raw).strip()
    if not text or text.lower() in {"nan", "none", "null"}:
        return float("nan")
    return float(text)


def load_rows(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append(
                {
                    "drone_count": int(row["drone_count"]),
                    "method_id": row["method_id"],
                    "method_label": row["method_label"],
                    "method_family": row["method_family"],
                    "strict_quality": parse_float(row["mean_scene_expected_strict_quality"]),
                    "delta_vs_single": parse_float(row["delta_vs_single_reference_strict_quality"]),
                }
            )
    return rows


def select_top_rows(rows: list[dict[str, object]], drone_count: int, top_n: int) -> list[dict[str, object]]:
    filtered = [
        row
        for row in rows
        if int(row["drone_count"]) == drone_count and str(row["method_id"]) != "single_view_reference"
    ]
    filtered.sort(
        key=lambda row: (-float(row["strict_quality"]), str(row["method_label"])),
    )
    return filtered[:top_n]


def build_comparison_rows(
    all_rows: list[dict[str, object]], top_two: list[dict[str, object]], top_three: list[dict[str, object]]
) -> list[dict[str, object]]:
    lookup = {(int(row["drone_count"]), str(row["method_id"])): row for row in all_rows}

    rank_two = {str(row["method_id"]): index + 1 for index, row in enumerate(top_two)}
    rank_three = {str(row["method_id"]): index + 1 for index, row in enumerate(top_three)}

    ordered_method_ids: list[str] = []
    for row in top_three + top_two:
        method_id = str(row["method_id"])
        if method_id not in ordered_method_ids:
            ordered_method_ids.append(method_id)

    comparison_rows: list[dict[str, object]] = []
    for method_id in ordered_method_ids:
        row_two = lookup.get((2, method_id))
        row_three = lookup.get((3, method_id))
        label = ""
        family = ""
        if row_three is not None:
            label = str(row_three["method_label"])
            family = str(row_three["method_family"])
        elif row_two is not None:
            label = str(row_two["method_label"])
            family = str(row_two["method_family"])

        comparison_rows.append(
            {
                "method_id": method_id,
                "method_label": label,
                "method_family": family,
                "rank_2": rank_two.get(method_id, ""),
                "strict_quality_2": float(row_two["strict_quality"]) if row_two is not None else float("nan"),
                "delta_vs_single_2": float(row_two["delta_vs_single"]) if row_two is not None else float("nan"),
                "rank_3": rank_three.get(method_id, ""),
                "strict_quality_3": float(row_three["strict_quality"]) if row_three is not None else float("nan"),
                "delta_vs_single_3": float(row_three["delta_vs_single"]) if row_three is not None else float("nan"),
            }
        )
    return comparison_rows


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fieldnames = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def plot_rows(rows: list[dict[str, object]], baseline: float, output_path: Path) -> None:
    method_labels = [str(row["method_label"]) for row in rows]
    y = np.arange(len(rows))
    bar_height = 0.34

    values_2 = [float(row["strict_quality_2"]) for row in rows]
    values_3 = [float(row["strict_quality_3"]) for row in rows]

    xmin = min([baseline] + [value for value in values_2 + values_3 if not math.isnan(value)]) - 0.01
    xmax = max([baseline] + [value for value in values_2 + values_3 if not math.isnan(value)]) + 0.012

    fig, ax = plt.subplots(figsize=(12.5, 7.4), constrained_layout=True)
    ax.axvline(baseline, color="#4a5568", linestyle="--", linewidth=1.6, label=f"1-view baseline ({baseline:.4f})")

    bars_2 = ax.barh(
        y + bar_height / 2,
        values_2,
        height=bar_height,
        color="#5b8cc0",
        alpha=0.95,
        edgecolor="white",
        label="2 views",
    )
    bars_3 = ax.barh(
        y - bar_height / 2,
        values_3,
        height=bar_height,
        color="#d97706",
        alpha=0.95,
        edgecolor="white",
        hatch="///",
        label="3 views",
    )

    ax.set_yticks(y, method_labels)
    ax.invert_yaxis()
    ax.set_xlim(xmin, xmax)
    ax.set_xlabel("Scene-balanced strict quality")
    ax.set_title("Top 5 coalition methods: 2 views versus 3 views")
    ax.grid(axis="x", linestyle="--", alpha=0.25)

    for index, (bar_2, bar_3, row) in enumerate(zip(bars_2, bars_3, rows, strict=False)):
        value_2 = float(row["strict_quality_2"])
        value_3 = float(row["strict_quality_3"])

        if not math.isnan(value_2):
            ax.text(
                value_2 + 0.0012,
                bar_2.get_y() + bar_2.get_height() / 2,
                f"#{row['rank_2']}  {value_2:.4f}",
                va="center",
                ha="left",
                fontsize=10,
                color="#1a202c",
            )
        if not math.isnan(value_3):
            ax.text(
                value_3 + 0.0012,
                bar_3.get_y() + bar_3.get_height() / 2,
                f"#{row['rank_3']}  {value_3:.4f}",
                va="center",
                ha="left",
                fontsize=10,
                color="#1a202c",
            )

    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles, labels, loc="lower right", frameon=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    summary_csv = Path(args.summary_csv)
    output_png = Path(args.output_png)
    output_csv = Path(args.output_csv)

    rows = load_rows(summary_csv)
    baseline_row = next(row for row in rows if int(row["drone_count"]) == 1 and str(row["method_id"]) == "single_view_reference")
    baseline = float(baseline_row["strict_quality"])

    top_two = select_top_rows(rows, drone_count=2, top_n=args.top_n)
    top_three = select_top_rows(rows, drone_count=3, top_n=args.top_n)
    comparison_rows = build_comparison_rows(rows, top_two, top_three)

    write_csv(output_csv, comparison_rows)
    plot_rows(comparison_rows, baseline, output_png)


if __name__ == "__main__":
    main()
