from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401


ELEVATION_Z = {"low": 0.0, "mid": 12.0, "high": 24.0}
RADIUS_SIZE = {"near": 10.0, "mid": 18.0, "far": 26.0}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize the best viewpoint per object in a 3D summary figure."
    )
    parser.add_argument(
        "--report-csv",
        default="comparison_output/best_viewpoint_report_s0_m4/best_viewpoint_report_ap50_95.csv",
        help="CSV generated by create_best_viewpoint_report.py.",
    )
    parser.add_argument(
        "--label",
        default="S0_M4",
        help="Model label shown in the title.",
    )
    parser.add_argument(
        "--mode",
        choices=["single", "average"],
        default="average",
        help="Use best single viewpoint or best average viewpoint from the report CSV.",
    )
    parser.add_argument(
        "--output",
        default="comparison_output/best_viewpoint_report_s0_m4/best_viewpoint_3d.png",
        help="Output PNG path.",
    )
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def azimuth_to_xy(azimuth_deg: float, radius: float) -> tuple[float, float]:
    theta = math.radians(azimuth_deg)
    x = radius * math.cos(theta)
    y = radius * math.sin(theta)
    return x, y


def row_to_point(row: dict[str, str], mode: str) -> tuple[float, float, float, str]:
    if mode == "single":
        azimuth = float(row["best_single_azimuth"])
        elevation = row["best_single_elevation"]
        radius = row["best_single_radius"]
    else:
        azimuth = float(row["best_average_azimuth"])
        elevation = row["best_average_elevation"]
        radius = row["best_average_radius"]

    r = RADIUS_SIZE[radius]
    z = ELEVATION_Z[elevation]
    x, y = azimuth_to_xy(azimuth, r)
    label = row["class_name"]
    return x, y, z, label


def draw_reference_rings(ax) -> None:
    angles = np.linspace(0, 2 * np.pi, 200)
    colors = {"near": "#9ecae1", "mid": "#6baed6", "far": "#3182bd"}

    for elevation, z in ELEVATION_Z.items():
        for radius, r in RADIUS_SIZE.items():
            x = r * np.cos(angles)
            y = r * np.sin(angles)
            ax.plot(x, y, np.full_like(x, z), color=colors[radius], alpha=0.45, linewidth=1.5)


def create_figure(rows: list[dict[str, str]], label: str, mode: str, output_path: Path) -> None:
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection="3d")

    draw_reference_rings(ax)

    cmap = plt.get_cmap("tab10")
    for idx, row in enumerate(rows):
        x, y, z, object_label = row_to_point(row, mode)
        color = cmap(idx % 10)
        ax.scatter(x, y, z, s=300, color=color, edgecolor="black", linewidth=1.2, label=object_label)
        ax.text(x, y, z + 1.3, object_label, fontsize=9, ha="center", va="bottom")

    ax.set_title(
        f"Best {'single' if mode == 'single' else 'average'} viewpoint per object for {label}",
        fontsize=17,
        pad=20,
    )
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("elevation")
    ax.set_zticks(list(ELEVATION_Z.values()))
    ax.set_zticklabels(list(ELEVATION_Z.keys()))
    ax.view_init(elev=24, azim=45)
    ax.legend(title="Object", bbox_to_anchor=(1.02, 0.5), loc="center left")
    fig.tight_layout()
    fig.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    report_csv = Path(args.report_csv).resolve()
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    rows = read_rows(report_csv)
    create_figure(rows, args.label, args.mode, output_path)
    print(f"Saved 3D viewpoint figure to: {output_path}")


if __name__ == "__main__":
    main()



# python plot_best_viewpoint_3d.py `
#   --report-csv ".\comparison_output\best_viewpoint_report_s0_m4\best_viewpoint_report_ap50_95.csv" `
#   --label "S0_M4" `
#   --mode average `
#   --output ".\comparison_output\best_viewpoint_report_s0_m4\best_viewpoint_3d_average.png"
