from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rank best and worst viewpoint groups per object from cached viewpoint summaries."
    )
    parser.add_argument(
        "--summary-csv",
        default="comparison_output/object_viewpoint_boxplots_s0_m4/viewpoint_summary_ap50_95.csv",
        help="Summary CSV generated by plot_object_viewpoint_boxplots.py.",
    )
    parser.add_argument(
        "--output-csv",
        default="comparison_output/object_viewpoint_boxplots_s0_m4/viewpoint_best_worst_ap50_95.csv",
        help="Destination CSV for best/worst viewpoint ranking.",
    )
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def to_float(row: dict[str, str], key: str) -> float:
    return float(row[key])


def main() -> None:
    args = parse_args()
    summary_csv = Path(args.summary_csv).resolve()
    output_csv = Path(args.output_csv).resolve()
    rows = read_rows(summary_csv)

    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["class_name"], row["group_type"])].append(row)

    output_rows: list[dict[str, str | float]] = []
    for (class_name, group_type), group_rows in sorted(grouped.items()):
        ordered = sorted(group_rows, key=lambda row: to_float(row, "median"))
        worst_row = ordered[0]
        best_row = ordered[-1]
        output_rows.append(
            {
                "class_name": class_name,
                "group_type": group_type,
                "best_group": best_row["group_value"],
                "best_median": to_float(best_row, "median"),
                "best_mean": to_float(best_row, "mean"),
                "worst_group": worst_row["group_value"],
                "worst_median": to_float(worst_row, "median"),
                "worst_mean": to_float(worst_row, "mean"),
                "median_gap": to_float(best_row, "median") - to_float(worst_row, "median"),
            }
        )

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "class_name",
                "group_type",
                "best_group",
                "best_median",
                "best_mean",
                "worst_group",
                "worst_median",
                "worst_mean",
                "median_gap",
            ],
        )
        writer.writeheader()
        writer.writerows(output_rows)

    print(f"Saved best/worst viewpoint ranking to: {output_csv}")


if __name__ == "__main__":
    main()
